package catalog

import (
	_ "embed"
)

// This file handles embedded catalog data for zero-dependency deployment.
// The catalog data files are generated using the catalog-gen tool and
// embedded at compile time.
//
// To generate embedded data:
//   go run cmd/catalog-gen/main.go
//
// This will create the following files in internal/catalog/data/:
//   - hipparcos.bin.gz - Compressed Hipparcos star catalog
//   - messier.json.gz  - Compressed Messier catalog
//   - ngc.json.gz      - Compressed NGC catalog
//   - ic.json.gz       - Compressed IC catalog
//   - star_names.json  - Common star names
//
// The files are embedded using go:embed directives below.

// Embedded Hipparcos star catalog (generated by cmd/catalog-gen)
//
//go:embed data/hipparcos.bin.gz
var embeddedHipparcosDataFile []byte

// Note: Other embedded data files are commented out until generated.
// //go:embed data/messier.json.gz
// var embeddedMessierDataFile []byte

// //go:embed data/ngc.json.gz
// var embeddedNGCDataFile []byte

// //go:embed data/ic.json.gz
// var embeddedICDataFile []byte

// init registers the embedded data with the catalog loaders.
func init() {
	SetEmbeddedData(embeddedHipparcosDataFile)
}

// MessierCatalogData contains the complete Messier catalog with descriptions.
// This is a curated list suitable for educational purposes and challenges.
var MessierCatalogData = []DeepSkyObject{
	{ID: "M1", CommonName: "Crab Nebula", RA: 83.6333, Dec: 22.0167, Type: ObjectTypeNebula, VMag: 8.4, MajorAxis: 6, MinorAxis: 4, Constellation: "Taurus", Description: "Supernova remnant, pulsar at center", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M1.png", ImageCredit: "Stephane Dumont"},
	{ID: "M2", CommonName: "", RA: 323.3625, Dec: -0.8233, Type: ObjectTypeGlobular, VMag: 6.5, MajorAxis: 16, MinorAxis: 16, Constellation: "Aquarius", Description: "Rich globular cluster, 37000 light-years distant", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M2.png", ImageCredit: "Starhopper"},
	{ID: "M3", CommonName: "", RA: 205.5483, Dec: 28.3772, Type: ObjectTypeGlobular, VMag: 6.2, MajorAxis: 18, MinorAxis: 18, Constellation: "Canes Venatici", Description: "One of the brightest globular clusters", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M3.png", ImageCredit: "Starhopper"},
	{ID: "M4", CommonName: "", RA: 245.8967, Dec: -26.5256, Type: ObjectTypeGlobular, VMag: 5.6, MajorAxis: 36, MinorAxis: 36, Constellation: "Scorpius", Description: "Nearest globular cluster, near Antares", Difficulty: 1, MinExposure: 1800, ImageURL: "/dso-images/M4.png", ImageCredit: "Starhopper"},
	{ID: "M5", CommonName: "", RA: 229.6383, Dec: 2.0811, Type: ObjectTypeGlobular, VMag: 5.6, MajorAxis: 23, MinorAxis: 23, Constellation: "Serpens", Description: "Fine globular cluster, over 100000 stars", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M5.png", ImageCredit: "Starhopper"},
	{ID: "M6", CommonName: "Butterfly Cluster", RA: 265.0833, Dec: -32.2167, Type: ObjectTypeOpenCluster, VMag: 4.2, MajorAxis: 25, MinorAxis: 25, Constellation: "Scorpius", Description: "Open cluster resembling a butterfly", Difficulty: 1, MinExposure: 900, ImageURL: "/dso-images/M6.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M7", CommonName: "Ptolemy Cluster", RA: 268.4667, Dec: -34.7933, Type: ObjectTypeOpenCluster, VMag: 3.3, MajorAxis: 80, MinorAxis: 80, Constellation: "Scorpius", Description: "Large bright open cluster, known since antiquity", Difficulty: 1, MinExposure: 600, ImageURL: "/dso-images/M7.png", ImageCredit: "ESO, Sun Shuwei"},
	{ID: "M8", CommonName: "Lagoon Nebula", RA: 270.9208, Dec: -24.3833, Type: ObjectTypeNebula, VMag: 6.0, MajorAxis: 90, MinorAxis: 40, Constellation: "Sagittarius", Description: "Bright emission nebula with open cluster NGC 6530", Difficulty: 1, MinExposure: 1800, ImageURL: "/dso-images/M8.png", ImageCredit: "Dylan O'Donnell"},
	{ID: "M9", CommonName: "", RA: 259.7983, Dec: -18.5161, Type: ObjectTypeGlobular, VMag: 7.7, MajorAxis: 12, MinorAxis: 12, Constellation: "Ophiuchus", Description: "Globular cluster near galactic center", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M9.png", ImageCredit: "Sun Shuwei"},
	{ID: "M10", CommonName: "", RA: 254.2875, Dec: -4.1003, Type: ObjectTypeGlobular, VMag: 6.6, MajorAxis: 20, MinorAxis: 20, Constellation: "Ophiuchus", Description: "Bright globular cluster in Ophiuchus", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M10.png", ImageCredit: "Starhopper"},
	{ID: "M11", CommonName: "Wild Duck Cluster", RA: 282.7667, Dec: -6.2667, Type: ObjectTypeOpenCluster, VMag: 6.3, MajorAxis: 14, MinorAxis: 14, Constellation: "Scutum", Description: "Very rich compact open cluster", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M11.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M12", CommonName: "", RA: 251.8092, Dec: -1.9483, Type: ObjectTypeGlobular, VMag: 6.7, MajorAxis: 16, MinorAxis: 16, Constellation: "Ophiuchus", Description: "Loose globular cluster in Ophiuchus", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M12.png", ImageCredit: "Hewholooks"},
	{ID: "M13", CommonName: "Great Hercules Cluster", RA: 250.4217, Dec: 36.4614, Type: ObjectTypeGlobular, VMag: 5.8, MajorAxis: 20, MinorAxis: 20, Constellation: "Hercules", Description: "Finest globular cluster in the northern sky", Difficulty: 1, MinExposure: 3600, ImageURL: "/dso-images/M13.png", ImageCredit: "Starhopper"},
	{ID: "M14", CommonName: "", RA: 264.4008, Dec: -3.2458, Type: ObjectTypeGlobular, VMag: 7.6, MajorAxis: 11, MinorAxis: 11, Constellation: "Ophiuchus", Description: "Globular cluster with many variable stars", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M14.png", ImageCredit: "Hewholooks"},
	{ID: "M15", CommonName: "", RA: 322.4930, Dec: 12.1670, Type: ObjectTypeGlobular, VMag: 6.2, MajorAxis: 18, MinorAxis: 18, Constellation: "Pegasus", Description: "Dense globular cluster, possible black hole at center", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M15.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M16", CommonName: "Eagle Nebula", RA: 274.7000, Dec: -13.7833, Type: ObjectTypeClusterNebula, VMag: 6.0, MajorAxis: 35, MinorAxis: 28, Constellation: "Serpens", Description: "Pillars of Creation, star-forming region", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M16.png", ImageCredit: "Sun Gang"},
	{ID: "M17", CommonName: "Omega Nebula", RA: 275.1958, Dec: -16.1731, Type: ObjectTypeNebula, VMag: 6.0, MajorAxis: 46, MinorAxis: 37, Constellation: "Sagittarius", Description: "Bright emission nebula, also called Swan Nebula", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M17.png", ImageCredit: "Dylan O'Donnell"},
	{ID: "M18", CommonName: "", RA: 274.2917, Dec: -17.1167, Type: ObjectTypeOpenCluster, VMag: 7.5, MajorAxis: 9, MinorAxis: 9, Constellation: "Sagittarius", Description: "Small sparse open cluster near M17", Difficulty: 3, MinExposure: 1800, ImageURL: "/dso-images/M18.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M19", CommonName: "", RA: 255.6567, Dec: -26.2681, Type: ObjectTypeGlobular, VMag: 6.8, MajorAxis: 17, MinorAxis: 13, Constellation: "Ophiuchus", Description: "Oblate globular cluster near galactic center", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M19.png", ImageCredit: "NOIRLab/NSF/AURA, Sun Shuwei"},
	{ID: "M20", CommonName: "Trifid Nebula", RA: 270.6208, Dec: -23.0300, Type: ObjectTypeNebula, VMag: 6.3, MajorAxis: 28, MinorAxis: 28, Constellation: "Sagittarius", Description: "Emission, reflection, and dark nebula combined", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M20.png", ImageCredit: "Hewholooks"},
	{ID: "M21", CommonName: "", RA: 270.9792, Dec: -22.4917, Type: ObjectTypeOpenCluster, VMag: 6.5, MajorAxis: 13, MinorAxis: 13, Constellation: "Sagittarius", Description: "Open cluster near M20 Trifid Nebula", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M21.png", ImageCredit: "Trevor Gerdes"},
	{ID: "M22", CommonName: "Sagittarius Cluster", RA: 279.0983, Dec: -23.9047, Type: ObjectTypeGlobular, VMag: 5.1, MajorAxis: 32, MinorAxis: 32, Constellation: "Sagittarius", Description: "One of the nearest and brightest globular clusters", Difficulty: 1, MinExposure: 1800, ImageURL: "/dso-images/M22.png", ImageCredit: "Hewholooks"},
	{ID: "M23", CommonName: "", RA: 269.2667, Dec: -19.0167, Type: ObjectTypeOpenCluster, VMag: 6.9, MajorAxis: 27, MinorAxis: 27, Constellation: "Sagittarius", Description: "Rich open cluster in the Milky Way", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M23.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M24", CommonName: "Sagittarius Star Cloud", RA: 274.5375, Dec: -18.5167, Type: ObjectTypeOpenCluster, VMag: 4.6, MajorAxis: 90, MinorAxis: 90, Constellation: "Sagittarius", Description: "Dense Milky Way star cloud", Difficulty: 1, MinExposure: 1200, ImageURL: "/dso-images/M24.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M25", CommonName: "", RA: 277.8542, Dec: -19.1167, Type: ObjectTypeOpenCluster, VMag: 6.5, MajorAxis: 32, MinorAxis: 32, Constellation: "Sagittarius", Description: "Open cluster with Cepheid variable U Sgr", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M25.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M26", CommonName: "", RA: 281.3208, Dec: -9.3833, Type: ObjectTypeOpenCluster, VMag: 8.0, MajorAxis: 15, MinorAxis: 15, Constellation: "Scutum", Description: "Open cluster in Scutum star cloud", Difficulty: 3, MinExposure: 1800, ImageURL: "/dso-images/M26.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M27", CommonName: "Dumbbell Nebula", RA: 299.9017, Dec: 22.7211, Type: ObjectTypePlanetary, VMag: 7.5, MajorAxis: 8.0, MinorAxis: 5.7, Constellation: "Vulpecula", Description: "Brightest planetary nebula, first discovered", Difficulty: 1, MinExposure: 3600, ImageURL: "/dso-images/M27.png", ImageCredit: "Stephane Dumont"},
	{ID: "M28", CommonName: "", RA: 276.1367, Dec: -24.8703, Type: ObjectTypeGlobular, VMag: 6.8, MajorAxis: 11, MinorAxis: 11, Constellation: "Sagittarius", Description: "Globular cluster near Lambda Sagittarii", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M28.png", ImageCredit: "Starhopper"},
	{ID: "M29", CommonName: "", RA: 305.9667, Dec: 38.5167, Type: ObjectTypeOpenCluster, VMag: 7.1, MajorAxis: 7, MinorAxis: 7, Constellation: "Cygnus", Description: "Small open cluster in Cygnus", Difficulty: 3, MinExposure: 1800, ImageURL: "/dso-images/M29.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M30", CommonName: "", RA: 325.0917, Dec: -23.1797, Type: ObjectTypeGlobular, VMag: 7.2, MajorAxis: 12, MinorAxis: 12, Constellation: "Capricornus", Description: "Core-collapsed globular cluster", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M30.png", ImageCredit: "Starhopper"},
	{ID: "M31", CommonName: "Andromeda Galaxy", RA: 10.6833, Dec: 41.2692, Type: ObjectTypeGalaxy, VMag: 3.4, MajorAxis: 190, MinorAxis: 60, Constellation: "Andromeda", Morphology: GalaxySpiral, Description: "Nearest major galaxy, 2.5 million light-years", Difficulty: 1, MinExposure: 3600, ImageURL: "/dso-images/M31.png", ImageCredit: "LEE ang HG731GZ"},
	{ID: "M32", CommonName: "", RA: 10.6742, Dec: 40.8653, Type: ObjectTypeGalaxy, VMag: 8.1, MajorAxis: 9, MinorAxis: 7, Constellation: "Andromeda", Morphology: GalaxyElliptical, Description: "Satellite galaxy of M31, compact elliptical", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M32.jpg", ImageCredit: "DSS2/STScI/Caltech"},
	{ID: "M33", CommonName: "Triangulum Galaxy", RA: 23.4625, Dec: 30.6600, Type: ObjectTypeGalaxy, VMag: 5.7, MajorAxis: 73, MinorAxis: 45, Constellation: "Triangulum", Morphology: GalaxySpiral, Description: "Third-largest galaxy in Local Group", Difficulty: 2, MinExposure: 7200, ImageURL: "/dso-images/M33.png", ImageCredit: "HG731GZ"},
	{ID: "M34", CommonName: "", RA: 40.5167, Dec: 42.7833, Type: ObjectTypeOpenCluster, VMag: 5.5, MajorAxis: 35, MinorAxis: 35, Constellation: "Perseus", Description: "Bright open cluster visible to naked eye", Difficulty: 1, MinExposure: 900, ImageURL: "/dso-images/M34.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M35", CommonName: "", RA: 92.2500, Dec: 24.3333, Type: ObjectTypeOpenCluster, VMag: 5.3, MajorAxis: 28, MinorAxis: 28, Constellation: "Gemini", Description: "Large bright open cluster at foot of Gemini", Difficulty: 1, MinExposure: 900, ImageURL: "/dso-images/M35.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M36", CommonName: "", RA: 84.0833, Dec: 34.1333, Type: ObjectTypeOpenCluster, VMag: 6.3, MajorAxis: 12, MinorAxis: 12, Constellation: "Auriga", Description: "Open cluster in Auriga, youngest of three", Difficulty: 2, MinExposure: 1200, ImageURL: "/dso-images/M36.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M37", CommonName: "", RA: 88.0708, Dec: 32.5500, Type: ObjectTypeOpenCluster, VMag: 6.2, MajorAxis: 24, MinorAxis: 24, Constellation: "Auriga", Description: "Richest open cluster in Auriga", Difficulty: 2, MinExposure: 1200, ImageURL: "/dso-images/M37.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M38", CommonName: "", RA: 82.1667, Dec: 35.8333, Type: ObjectTypeOpenCluster, VMag: 7.4, MajorAxis: 21, MinorAxis: 21, Constellation: "Auriga", Description: "Open cluster in Auriga, cross-shaped pattern", Difficulty: 2, MinExposure: 1200, ImageURL: "/dso-images/M38.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M39", CommonName: "", RA: 322.3167, Dec: 48.4333, Type: ObjectTypeOpenCluster, VMag: 4.6, MajorAxis: 32, MinorAxis: 32, Constellation: "Cygnus", Description: "Loose open cluster, visible to naked eye", Difficulty: 1, MinExposure: 600, ImageURL: "/dso-images/M39.png", ImageCredit: "DSS"},
	{ID: "M40", CommonName: "Winnecke 4", RA: 185.5500, Dec: 58.0833, Type: ObjectTypeStar, VMag: 8.4, MajorAxis: 0.8, MinorAxis: 0.8, Constellation: "Ursa Major", Description: "Double star, not a deep sky object", Difficulty: 3, MinExposure: 600, ImageURL: "/dso-images/M40.jpg", ImageCredit: "DSS2/STScI/Caltech"},
	{ID: "M41", CommonName: "", RA: 101.5042, Dec: -20.7572, Type: ObjectTypeOpenCluster, VMag: 4.5, MajorAxis: 38, MinorAxis: 38, Constellation: "Canis Major", Description: "Bright open cluster south of Sirius", Difficulty: 1, MinExposure: 600, ImageURL: "/dso-images/M41.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M42", CommonName: "Orion Nebula", RA: 83.8208, Dec: -5.3911, Type: ObjectTypeNebula, VMag: 4.0, MajorAxis: 85, MinorAxis: 60, Constellation: "Orion", Description: "Closest massive star-forming region", Difficulty: 1, MinExposure: 300, ImageURL: "/dso-images/M42.png", ImageCredit: "HG731GZ"},
	{ID: "M43", CommonName: "De Mairan's Nebula", RA: 83.8917, Dec: -5.2667, Type: ObjectTypeNebula, VMag: 9.0, MajorAxis: 20, MinorAxis: 15, Constellation: "Orion", Description: "Part of Orion Nebula complex, separated by dark lane", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M43.jpg", ImageCredit: "DSS2/STScI/Caltech"},
	{ID: "M44", CommonName: "Beehive Cluster", RA: 130.0250, Dec: 19.6683, Type: ObjectTypeOpenCluster, VMag: 3.7, MajorAxis: 95, MinorAxis: 95, Constellation: "Cancer", Description: "Praesepe, large nearby open cluster", Difficulty: 1, MinExposure: 600, ImageURL: "/dso-images/M44.png", ImageCredit: "Giuseppe Donatiello"},
	{ID: "M45", CommonName: "Pleiades", RA: 56.8708, Dec: 24.1167, Type: ObjectTypeOpenCluster, VMag: 1.6, MajorAxis: 110, Constellation: "Taurus", Description: "Seven Sisters, reflection nebulosity", Difficulty: 1, MinExposure: 1800, ImageURL: "/dso-images/M45.png", ImageCredit: "HG731GZ"},
	{ID: "M46", CommonName: "", RA: 115.4375, Dec: -14.8167, Type: ObjectTypeOpenCluster, VMag: 6.1, MajorAxis: 27, MinorAxis: 27, Constellation: "Puppis", Description: "Rich open cluster with planetary nebula NGC 2438", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M46.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M47", CommonName: "", RA: 114.1500, Dec: -14.4833, Type: ObjectTypeOpenCluster, VMag: 4.2, MajorAxis: 30, MinorAxis: 30, Constellation: "Puppis", Description: "Bright open cluster near M46", Difficulty: 1, MinExposure: 600, ImageURL: "/dso-images/M47.png", ImageCredit: "Trevor Gerdes"},
	{ID: "M48", CommonName: "", RA: 123.4250, Dec: -5.8000, Type: ObjectTypeOpenCluster, VMag: 5.5, MajorAxis: 54, MinorAxis: 54, Constellation: "Hydra", Description: "Large open cluster in Hydra", Difficulty: 2, MinExposure: 1200, ImageURL: "/dso-images/M48.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M49", CommonName: "", RA: 187.4442, Dec: 8.0003, Type: ObjectTypeGalaxy, VMag: 8.4, MajorAxis: 10, MinorAxis: 8, Constellation: "Virgo", Morphology: GalaxyElliptical, Description: "Brightest galaxy in the Virgo Cluster", Difficulty: 2, MinExposure: 5400, ImageURL: "/dso-images/M49.png", ImageCredit: "SDSS"},
	{ID: "M50", CommonName: "", RA: 105.6917, Dec: -8.3500, Type: ObjectTypeOpenCluster, VMag: 5.9, MajorAxis: 16, MinorAxis: 16, Constellation: "Monoceros", Description: "Open cluster in Monoceros", Difficulty: 2, MinExposure: 1200, ImageURL: "/dso-images/M50.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M51", CommonName: "Whirlpool Galaxy", RA: 202.4696, Dec: 47.1953, Type: ObjectTypeGalaxy, VMag: 8.4, MajorAxis: 11, MinorAxis: 7, Constellation: "Canes Venatici", Morphology: GalaxySpiral, Description: "Face-on spiral with companion NGC 5195", Difficulty: 2, MinExposure: 7200, ImageURL: "/dso-images/M51.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M52", CommonName: "", RA: 351.2042, Dec: 61.5833, Type: ObjectTypeOpenCluster, VMag: 7.3, MajorAxis: 13, MinorAxis: 13, Constellation: "Cassiopeia", Description: "Rich open cluster in Cassiopeia", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M52.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M53", CommonName: "", RA: 198.2292, Dec: 18.1681, Type: ObjectTypeGlobular, VMag: 7.6, MajorAxis: 13, MinorAxis: 13, Constellation: "Coma Berenices", Description: "Remote globular cluster, 58000 light-years distant", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M53.png", ImageCredit: "Starhopper"},
	{ID: "M54", CommonName: "", RA: 283.7633, Dec: -30.4783, Type: ObjectTypeGlobular, VMag: 7.6, MajorAxis: 12, MinorAxis: 12, Constellation: "Sagittarius", Description: "Extragalactic globular in Sagittarius Dwarf Galaxy", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M54.png", ImageCredit: "NOIRLab/NSF/AURA, Sun Shuwei"},
	{ID: "M55", CommonName: "", RA: 294.9983, Dec: -30.9647, Type: ObjectTypeGlobular, VMag: 6.3, MajorAxis: 19, MinorAxis: 19, Constellation: "Sagittarius", Description: "Loose globular cluster, relatively nearby", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M55.png", ImageCredit: "Hewholooks"},
	{ID: "M56", CommonName: "", RA: 289.1483, Dec: 30.1842, Type: ObjectTypeGlobular, VMag: 8.3, MajorAxis: 9, MinorAxis: 9, Constellation: "Lyra", Description: "Globular cluster between Albireo and Sulafat", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M56.png", ImageCredit: "Hewholooks"},
	{ID: "M57", CommonName: "Ring Nebula", RA: 283.3958, Dec: 33.0286, Type: ObjectTypePlanetary, VMag: 8.8, MajorAxis: 1.4, MinorAxis: 1.0, Constellation: "Lyra", Description: "Classic planetary nebula", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M57.png", ImageCredit: "Stephane Dumont"},
	{ID: "M58", CommonName: "", RA: 189.4313, Dec: 11.8183, Type: ObjectTypeGalaxy, VMag: 9.7, MajorAxis: 6, MinorAxis: 5, Constellation: "Virgo", Morphology: GalaxyBarred, Description: "Barred spiral in the Virgo Cluster", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M58.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M59", CommonName: "", RA: 190.5092, Dec: 11.6472, Type: ObjectTypeGalaxy, VMag: 9.6, MajorAxis: 5, MinorAxis: 4, Constellation: "Virgo", Morphology: GalaxyElliptical, Description: "Elliptical galaxy in Virgo Cluster", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M59.png", ImageCredit: "SDSS"},
	{ID: "M60", CommonName: "", RA: 190.9167, Dec: 11.5525, Type: ObjectTypeGalaxy, VMag: 8.8, MajorAxis: 7, MinorAxis: 6, Constellation: "Virgo", Morphology: GalaxyElliptical, Description: "Giant elliptical in Virgo Cluster", Difficulty: 3, MinExposure: 5400, ImageURL: "/dso-images/M60.png", ImageCredit: "SDSS"},
	{ID: "M61", CommonName: "", RA: 185.4788, Dec: 4.4736, Type: ObjectTypeGalaxy, VMag: 9.7, MajorAxis: 6, MinorAxis: 5, Constellation: "Virgo", Morphology: GalaxyBarred, Description: "Face-on barred spiral with active nucleus", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M61.png", ImageCredit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona"},
	{ID: "M62", CommonName: "", RA: 255.3033, Dec: -30.1119, Type: ObjectTypeGlobular, VMag: 6.5, MajorAxis: 15, MinorAxis: 15, Constellation: "Ophiuchus", Description: "Irregular-shaped globular near galactic center", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M62.png", ImageCredit: "Hewholooks"},
	{ID: "M63", CommonName: "Sunflower Galaxy", RA: 198.9554, Dec: 42.0294, Type: ObjectTypeGalaxy, VMag: 8.6, MajorAxis: 13, MinorAxis: 8, Constellation: "Canes Venatici", Morphology: GalaxySpiral, Description: "Flocculent spiral with patchy arms", Difficulty: 2, MinExposure: 7200, ImageURL: "/dso-images/M63.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M64", CommonName: "Black Eye Galaxy", RA: 194.1825, Dec: 21.6828, Type: ObjectTypeGalaxy, VMag: 8.5, MajorAxis: 10, MinorAxis: 5, Constellation: "Coma Berenices", Morphology: GalaxySpiral, Description: "Prominent dark dust band in front of nucleus", Difficulty: 2, MinExposure: 5400, ImageURL: "/dso-images/M64.png", ImageCredit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona"},
	{ID: "M65", CommonName: "", RA: 169.7330, Dec: 13.0922, Type: ObjectTypeGalaxy, VMag: 9.3, MajorAxis: 10, MinorAxis: 3, Constellation: "Leo", Morphology: GalaxySpiral, Description: "Leo Triplet member, edge-on spiral", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M65.png", ImageCredit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona"},
	{ID: "M66", CommonName: "", RA: 170.0625, Dec: 12.9914, Type: ObjectTypeGalaxy, VMag: 8.9, MajorAxis: 9, MinorAxis: 4, Constellation: "Leo", Morphology: GalaxyBarred, Description: "Leo Triplet member, asymmetric spiral arms", Difficulty: 2, MinExposure: 7200, ImageURL: "/dso-images/M66.png", ImageCredit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona"},
	{ID: "M67", CommonName: "", RA: 132.8250, Dec: 11.8167, Type: ObjectTypeOpenCluster, VMag: 6.1, MajorAxis: 30, MinorAxis: 30, Constellation: "Cancer", Description: "One of the oldest known open clusters, 4 billion years", Difficulty: 2, MinExposure: 1800, ImageURL: "/dso-images/M67.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M68", CommonName: "", RA: 189.8667, Dec: -26.7444, Type: ObjectTypeGlobular, VMag: 7.8, MajorAxis: 11, MinorAxis: 11, Constellation: "Hydra", Description: "Globular cluster in Hydra, metal-poor", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M68.png", ImageCredit: "Sun Shuwei"},
	{ID: "M69", CommonName: "", RA: 277.8463, Dec: -32.3481, Type: ObjectTypeGlobular, VMag: 7.6, MajorAxis: 9, MinorAxis: 9, Constellation: "Sagittarius", Description: "Small globular near galactic center", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M69.png", ImageCredit: "Starhopper"},
	{ID: "M70", CommonName: "", RA: 280.8038, Dec: -32.2942, Type: ObjectTypeGlobular, VMag: 7.9, MajorAxis: 8, MinorAxis: 8, Constellation: "Sagittarius", Description: "Core-collapsed globular cluster", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M70.png", ImageCredit: "NOIRLab/NSF/AURA, Sun Shuwei"},
	{ID: "M71", CommonName: "", RA: 298.4438, Dec: 18.7792, Type: ObjectTypeGlobular, VMag: 8.2, MajorAxis: 7, MinorAxis: 7, Constellation: "Sagitta", Description: "Loose globular cluster, resembles open cluster", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M71.png", ImageCredit: "Starhopper"},
	{ID: "M72", CommonName: "", RA: 313.3650, Dec: -12.5372, Type: ObjectTypeGlobular, VMag: 9.3, MajorAxis: 6, MinorAxis: 6, Constellation: "Aquarius", Description: "Remote faint globular cluster", Difficulty: 4, MinExposure: 5400, ImageURL: "/dso-images/M72.png", ImageCredit: "Starhopper, Sun Shuwei"},
	{ID: "M73", CommonName: "", RA: 314.7492, Dec: -12.6333, Type: ObjectTypeOpenCluster, VMag: 9.0, MajorAxis: 3, MinorAxis: 3, Constellation: "Aquarius", Description: "Asterism of four stars, not a true cluster", Difficulty: 4, MinExposure: 1800, ImageURL: "/dso-images/M73.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M74", CommonName: "Phantom Galaxy", RA: 24.1742, Dec: 15.7836, Type: ObjectTypeGalaxy, VMag: 9.4, MajorAxis: 10, MinorAxis: 10, Constellation: "Pisces", Morphology: GalaxySpiral, Description: "Face-on grand design spiral, low surface brightness", Difficulty: 4, MinExposure: 10800, ImageURL: "/dso-images/M74.png", ImageCredit: "Bart Delsaert"},
	{ID: "M75", CommonName: "", RA: 301.5200, Dec: -21.9211, Type: ObjectTypeGlobular, VMag: 8.5, MajorAxis: 6, MinorAxis: 6, Constellation: "Sagittarius", Description: "Highly concentrated globular cluster", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M75.png", ImageCredit: "Starhopper"},
	{ID: "M76", CommonName: "Little Dumbbell Nebula", RA: 25.5821, Dec: 51.5753, Type: ObjectTypePlanetary, VMag: 10.1, MajorAxis: 2.7, MinorAxis: 1.8, Constellation: "Perseus", Description: "Bipolar planetary nebula, faintest Messier object", Difficulty: 4, MinExposure: 5400, ImageURL: "/dso-images/M76.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M77", CommonName: "Cetus A", RA: 40.6696, Dec: -0.0133, Type: ObjectTypeGalaxy, VMag: 8.9, MajorAxis: 7, MinorAxis: 6, Constellation: "Cetus", Morphology: GalaxyBarred, Description: "Seyfert galaxy with active galactic nucleus", Difficulty: 3, MinExposure: 5400, ImageURL: "/dso-images/M77.png", ImageCredit: "Wang Lingyi"},
	{ID: "M78", CommonName: "", RA: 86.6500, Dec: 0.0783, Type: ObjectTypeNebula, VMag: 8.3, MajorAxis: 8, MinorAxis: 6, Constellation: "Orion", Description: "Brightest reflection nebula in the sky", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M78.png", ImageCredit: "Manuel Peitsch, Sun Shuwei"},
	{ID: "M79", CommonName: "", RA: 81.0442, Dec: -24.5247, Type: ObjectTypeGlobular, VMag: 7.7, MajorAxis: 9, MinorAxis: 9, Constellation: "Lepus", Description: "Winter globular cluster, possibly captured", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M79.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M80", CommonName: "", RA: 244.2600, Dec: -22.9756, Type: ObjectTypeGlobular, VMag: 7.3, MajorAxis: 10, MinorAxis: 10, Constellation: "Scorpius", Description: "Dense globular cluster, 1860 nova observed", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M80.png", ImageCredit: "NOIRLab/NSF/AURA, Sun Shuwei"},
	{ID: "M81", CommonName: "Bode's Galaxy", RA: 148.8883, Dec: 69.0653, Type: ObjectTypeGalaxy, VMag: 6.9, MajorAxis: 27, MinorAxis: 14, Constellation: "Ursa Major", Morphology: GalaxySpiral, Description: "Grand design spiral", Difficulty: 2, MinExposure: 5400, ImageURL: "/dso-images/M81.png", ImageCredit: "Kees Scherer, Sun Shuwei"},
	{ID: "M82", CommonName: "Cigar Galaxy", RA: 148.9683, Dec: 69.6797, Type: ObjectTypeGalaxy, VMag: 8.4, MajorAxis: 11, MinorAxis: 4, Constellation: "Ursa Major", Morphology: GalaxyIrregular, Description: "Starburst galaxy, M81's companion", Difficulty: 2, MinExposure: 5400, ImageURL: "/dso-images/M82.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M83", CommonName: "Southern Pinwheel Galaxy", RA: 204.2538, Dec: -29.8656, Type: ObjectTypeGalaxy, VMag: 7.6, MajorAxis: 13, MinorAxis: 12, Constellation: "Hydra", Morphology: GalaxyBarred, Description: "Barred spiral, prolific supernova producer", Difficulty: 2, MinExposure: 5400, ImageURL: "/dso-images/M83.png", ImageCredit: "TRAPPIST/E. Jehin/ESO"},
	{ID: "M84", CommonName: "", RA: 186.2654, Dec: 12.8869, Type: ObjectTypeGalaxy, VMag: 9.1, MajorAxis: 6, MinorAxis: 5, Constellation: "Virgo", Morphology: GalaxyLenticular, Description: "Lenticular galaxy in Markarian's Chain", Difficulty: 3, MinExposure: 5400, ImageURL: "/dso-images/M84.jpg", ImageCredit: "DSS2/STScI/Caltech"},
	{ID: "M85", CommonName: "", RA: 186.3500, Dec: 18.1911, Type: ObjectTypeGalaxy, VMag: 9.1, MajorAxis: 7, MinorAxis: 5, Constellation: "Coma Berenices", Morphology: GalaxyLenticular, Description: "Lenticular galaxy, northernmost Virgo Cluster member", Difficulty: 3, MinExposure: 5400, ImageURL: "/dso-images/M85.png", ImageCredit: "Starhopper"},
	{ID: "M86", CommonName: "", RA: 186.5488, Dec: 12.9461, Type: ObjectTypeGalaxy, VMag: 8.9, MajorAxis: 9, MinorAxis: 6, Constellation: "Virgo", Morphology: GalaxyLenticular, Description: "Lenticular galaxy in Markarian's Chain, blueshifted", Difficulty: 3, MinExposure: 5400, ImageURL: "/dso-images/M86.jpg", ImageCredit: "DSS2/STScI/Caltech"},
	{ID: "M87", CommonName: "Virgo A", RA: 187.7058, Dec: 12.3911, Type: ObjectTypeGalaxy, VMag: 8.6, MajorAxis: 8, MinorAxis: 7, Constellation: "Virgo", Morphology: GalaxyElliptical, Description: "Giant elliptical, famous relativistic jet, supermassive black hole imaged", Difficulty: 2, MinExposure: 5400, ImageURL: "/dso-images/M87.jpg", ImageCredit: "DSS2/STScI/Caltech"},
	{ID: "M88", CommonName: "", RA: 188.9963, Dec: 14.4203, Type: ObjectTypeGalaxy, VMag: 9.6, MajorAxis: 7, MinorAxis: 4, Constellation: "Coma Berenices", Morphology: GalaxySpiral, Description: "Multi-armed spiral in Virgo Cluster", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M88.png", ImageCredit: "Hewholooks"},
	{ID: "M89", CommonName: "", RA: 188.9163, Dec: 12.5564, Type: ObjectTypeGalaxy, VMag: 9.8, MajorAxis: 5, MinorAxis: 5, Constellation: "Virgo", Morphology: GalaxyElliptical, Description: "Almost perfectly circular elliptical galaxy", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M89.png", ImageCredit: "ESO/DSS2"},
	{ID: "M90", CommonName: "", RA: 189.2092, Dec: 13.1628, Type: ObjectTypeGalaxy, VMag: 9.5, MajorAxis: 10, MinorAxis: 5, Constellation: "Virgo", Morphology: GalaxySpiral, Description: "Spiral galaxy moving toward us, blueshifted", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M90.png", ImageCredit: "NOIRLab/NSF/AURA, Sun Shuwei"},
	{ID: "M91", CommonName: "", RA: 188.8600, Dec: 14.4964, Type: ObjectTypeGalaxy, VMag: 10.2, MajorAxis: 5, MinorAxis: 4, Constellation: "Coma Berenices", Morphology: GalaxyBarred, Description: "Barred spiral, faintest Messier galaxy", Difficulty: 4, MinExposure: 10800, ImageURL: "/dso-images/M91.png", ImageCredit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona"},
	{ID: "M92", CommonName: "", RA: 259.2808, Dec: 43.1361, Type: ObjectTypeGlobular, VMag: 6.4, MajorAxis: 14, MinorAxis: 14, Constellation: "Hercules", Description: "Ancient globular cluster, one of the oldest known", Difficulty: 2, MinExposure: 3600, ImageURL: "/dso-images/M92.png", ImageCredit: "Hewholooks"},
	{ID: "M93", CommonName: "", RA: 116.1500, Dec: -23.8667, Type: ObjectTypeOpenCluster, VMag: 6.0, MajorAxis: 22, MinorAxis: 22, Constellation: "Puppis", Description: "Bright open cluster in Puppis", Difficulty: 2, MinExposure: 1200, ImageURL: "/dso-images/M93.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M94", CommonName: "Cat's Eye Galaxy", RA: 192.7213, Dec: 41.1203, Type: ObjectTypeGalaxy, VMag: 8.2, MajorAxis: 14, MinorAxis: 12, Constellation: "Canes Venatici", Morphology: GalaxySpiral, Description: "Starburst ring galaxy with bright nucleus", Difficulty: 2, MinExposure: 5400, ImageURL: "/dso-images/M94.png", ImageCredit: "Starhopper"},
	{ID: "M95", CommonName: "", RA: 160.9900, Dec: 11.7039, Type: ObjectTypeGalaxy, VMag: 9.7, MajorAxis: 7, MinorAxis: 5, Constellation: "Leo", Morphology: GalaxyBarred, Description: "Barred spiral in Leo I Group", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M95.png", ImageCredit: "Jschulman555"},
	{ID: "M96", CommonName: "", RA: 161.6904, Dec: 11.8197, Type: ObjectTypeGalaxy, VMag: 9.2, MajorAxis: 7, MinorAxis: 5, Constellation: "Leo", Morphology: GalaxySpiral, Description: "Brightest galaxy in Leo I Group", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M96.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M97", CommonName: "Owl Nebula", RA: 168.6988, Dec: 55.0192, Type: ObjectTypePlanetary, VMag: 9.9, MajorAxis: 3.4, MinorAxis: 3.3, Constellation: "Ursa Major", Description: "Planetary nebula with owl-like eyes", Difficulty: 3, MinExposure: 5400, ImageURL: "/dso-images/M97.png", ImageCredit: "Stephane Dumont"},
	{ID: "M98", CommonName: "", RA: 183.4513, Dec: 14.9003, Type: ObjectTypeGalaxy, VMag: 10.1, MajorAxis: 10, MinorAxis: 3, Constellation: "Coma Berenices", Morphology: GalaxySpiral, Description: "Nearly edge-on spiral, blueshifted", Difficulty: 4, MinExposure: 10800, ImageURL: "/dso-images/M98.png", ImageCredit: "Clh288"},
	{ID: "M99", CommonName: "Coma Pinwheel", RA: 184.7063, Dec: 14.4167, Type: ObjectTypeGalaxy, VMag: 9.9, MajorAxis: 5, MinorAxis: 5, Constellation: "Coma Berenices", Morphology: GalaxySpiral, Description: "Unbarred spiral with asymmetric arms", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M99.png", ImageCredit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona"},
	{ID: "M100", CommonName: "", RA: 185.7288, Dec: 15.8222, Type: ObjectTypeGalaxy, VMag: 9.3, MajorAxis: 7, MinorAxis: 6, Constellation: "Coma Berenices", Morphology: GalaxySpiral, Description: "Grand design spiral, Cepheid distance calibrator", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M100.png", ImageCredit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona"},
	{ID: "M101", CommonName: "Pinwheel Galaxy", RA: 210.8024, Dec: 54.3489, Type: ObjectTypeGalaxy, VMag: 7.9, MajorAxis: 29, MinorAxis: 27, Constellation: "Ursa Major", Morphology: GalaxySpiral, Description: "Face-on grand design spiral", Difficulty: 3, MinExposure: 10800, ImageURL: "/dso-images/M101.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M102", CommonName: "Spindle Galaxy", RA: 226.6233, Dec: 55.7636, Type: ObjectTypeGalaxy, VMag: 9.9, MajorAxis: 6, MinorAxis: 3, Constellation: "Draco", Morphology: GalaxyLenticular, Description: "Edge-on lenticular galaxy (NGC 5866)", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M102.png", ImageCredit: "Starhopper"},
	{ID: "M103", CommonName: "", RA: 23.3417, Dec: 60.6500, Type: ObjectTypeOpenCluster, VMag: 7.4, MajorAxis: 6, MinorAxis: 6, Constellation: "Cassiopeia", Description: "Small open cluster near Ruchbah", Difficulty: 2, MinExposure: 1200, ImageURL: "/dso-images/M103.png", ImageCredit: "Grasslands Observatory"},
	{ID: "M104", CommonName: "Sombrero Galaxy", RA: 190.0083, Dec: -11.6231, Type: ObjectTypeGalaxy, VMag: 8.0, MajorAxis: 9, MinorAxis: 4, Constellation: "Virgo", Morphology: GalaxyLenticular, Description: "Edge-on with prominent dust lane", Difficulty: 2, MinExposure: 5400, ImageURL: "/dso-images/M104.png", ImageCredit: "Adam Block/Mount Lemmon SkyCenter/University of Arizona"},
	{ID: "M105", CommonName: "", RA: 161.9567, Dec: 12.5817, Type: ObjectTypeGalaxy, VMag: 9.3, MajorAxis: 5, MinorAxis: 5, Constellation: "Leo", Morphology: GalaxyElliptical, Description: "Elliptical galaxy in Leo I Group", Difficulty: 3, MinExposure: 5400, ImageURL: "/dso-images/M105.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M106", CommonName: "", RA: 184.7400, Dec: 47.3042, Type: ObjectTypeGalaxy, VMag: 8.4, MajorAxis: 19, MinorAxis: 8, Constellation: "Canes Venatici", Morphology: GalaxySpiral, Description: "Seyfert galaxy with water maser emission", Difficulty: 2, MinExposure: 7200, ImageURL: "/dso-images/M106.png", ImageCredit: "Plover Hill Observatory"},
	{ID: "M107", CommonName: "", RA: 248.1333, Dec: -13.0536, Type: ObjectTypeGlobular, VMag: 7.9, MajorAxis: 13, MinorAxis: 13, Constellation: "Ophiuchus", Description: "Loose globular cluster, last Messier globular added", Difficulty: 3, MinExposure: 3600, ImageURL: "/dso-images/M107.png", ImageCredit: "Starhopper"},
	{ID: "M108", CommonName: "Surfboard Galaxy", RA: 167.8792, Dec: 55.6742, Type: ObjectTypeGalaxy, VMag: 10.0, MajorAxis: 8, MinorAxis: 2, Constellation: "Ursa Major", Morphology: GalaxyBarred, Description: "Edge-on barred spiral near M97 Owl Nebula", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M108.png", ImageCredit: "Hewholooks"},
	{ID: "M109", CommonName: "", RA: 179.3996, Dec: 53.3744, Type: ObjectTypeGalaxy, VMag: 9.8, MajorAxis: 8, MinorAxis: 5, Constellation: "Ursa Major", Morphology: GalaxyBarred, Description: "Barred spiral near Phecda in Ursa Major", Difficulty: 3, MinExposure: 7200, ImageURL: "/dso-images/M109.png", ImageCredit: "KPNO/NOIRLab/NSF/AURA, Sun Shuwei"},
	{ID: "M110", CommonName: "", RA: 10.0917, Dec: 41.6850, Type: ObjectTypeGalaxy, VMag: 8.5, MajorAxis: 22, MinorAxis: 11, Constellation: "Andromeda", Morphology: GalaxyElliptical, Description: "Satellite galaxy of M31, dwarf elliptical", Difficulty: 3, MinExposure: 5400, ImageURL: "/dso-images/M110.jpg", ImageCredit: "DSS2/STScI/Caltech"},
}

// BrightStarNames maps HIP numbers to common star names
// This is loaded during catalog initialization
var BrightStarNames = map[int]string{
	11767:  "Polaris",    // Alpha Ursae Minoris
	677:    "Alpheratz",  // Alpha Andromedae
	746:    "Caph",       // Beta Cassiopeiae
	1067:   "Algenib",    // Gamma Pegasi
	3179:   "Mirach",     // Beta Andromedae
	3419:   "Schedar",    // Alpha Cassiopeiae
	4427:   "Almach",     // Gamma Andromedae
	5447:   "Achird",     // Eta Cassiopeiae
	7588:   "Achernar",   // Alpha Eridani
	8102:   "Hamal",      // Alpha Arietis
	8903:   "Diphda",     // Beta Ceti
	9640:   "Mirfak",     // Alpha Persei
	13847:  "Aldebaran",  // Alpha Tauri
	14135:  "Rigel",      // Beta Orionis
	17702:  "Capella",    // Alpha Aurigae
	21421:  "Menkalinan", // Beta Aurigae
	24436:  "Bellatrix",  // Gamma Orionis
	24608:  "Mintaka",    // Delta Orionis
	25336:  "Alnilam",    // Epsilon Orionis
	25930:  "Alnitak",    // Zeta Orionis
	26311:  "Saiph",      // Kappa Orionis
	27989:  "Betelgeuse", // Alpha Orionis
	30438:  "Canopus",    // Alpha Carinae
	32349:  "Sirius",     // Alpha Canis Majoris
	33579:  "Adhara",     // Epsilon Canis Majoris
	34444:  "Wezen",      // Delta Canis Majoris
	36850:  "Castor",     // Alpha Geminorum
	37279:  "Procyon",    // Alpha Canis Minoris
	37826:  "Pollux",     // Beta Geminorum
	45238:  "Alphard",    // Alpha Hydrae
	49669:  "Regulus",    // Alpha Leonis
	54061:  "Dubhe",      // Alpha Ursae Majoris
	54872:  "Merak",      // Beta Ursae Majoris
	57632:  "Denebola",   // Beta Leonis
	58001:  "Phecda",     // Gamma Ursae Majoris
	59774:  "Megrez",     // Delta Ursae Majoris
	62956:  "Alioth",     // Epsilon Ursae Majoris
	65378:  "Mizar",      // Zeta Ursae Majoris
	67301:  "Alkaid",     // Eta Ursae Majoris
	68702:  "Spica",      // Alpha Virginis
	69673:  "Arcturus",   // Alpha Bootis
	71681:  "Proxima",    // Alpha Centauri C (closest star)
	71683:  "Rigil Kent", // Alpha Centauri A
	72622:  "Hadar",      // Beta Centauri
	80763:  "Antares",    // Alpha Scorpii
	85927:  "Rasalhague", // Alpha Ophiuchi
	86032:  "Shaula",     // Lambda Scorpii
	91262:  "Vega",       // Alpha Lyrae
	95947:  "Albireo",    // Beta Cygni
	97649:  "Altair",     // Alpha Aquilae
	102098: "Deneb",      // Alpha Cygni
	107315: "Fomalhaut",  // Alpha Piscis Austrini
	109268: "Enif",       // Epsilon Pegasi
	113368: "Markab",     // Alpha Pegasi
	113881: "Scheat",     // Beta Pegasi
}

// InitializeStarNames adds common names to a loaded Hipparcos catalog
func InitializeStarNames(catalog *HipparcosCatalog) {
	for hip, name := range BrightStarNames {
		catalog.AddStarName(name, hip)
	}
	catalog.RefreshBrightStarNames()
}

// InitializeMessierCatalog loads the built-in Messier catalog and finalizes it
func InitializeMessierCatalog(cat *DSOCatalogImpl) {
	for _, obj := range MessierCatalogData {
		cat.Add(obj)
	}
	cat.FinalizeLoad()
}
